# Paquetería

In [40]:
import pandas as pd
import matplotlib.pyplot as plt

# Datos del agua extraídos de siguiente [repositorio](https://github.com/cesar-xyz/MapatonAgua)

In [41]:
df = pd.read_csv('/Users/admin/Downloads/Semana_i/Datos/UnionRegiosDOFShape.csv')
cols = list(df.columns)
# Muestra listado de columnas
cols

['Column1',
 'TITULO',
 'USO QUE AMPARA EL TITULO',
 'TITULAR',
 'VOLUMEN DE EXTRACCIÓN ANUAL DE AGUAS NACIONALES QUE AMPARA EL TITULO EN m3',
 'APROVECHAMIENTOS SUPERFICIALES QUE AMPARA EL TITULO',
 'VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUPERFICIALES EN m3',
 'APROVECHAMIENTOS SUBTERRÁNEOS QUE AMPARA EL TITULO',
 'VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUBTERRÁNEOS EN m3',
 'PUNTOS DE DESCARGA QUE AMPARA EL TITULO',
 'VOLUMEN DE DESCARGA DIARIO EN m3',
 'ZONAS FEDERALES QUE AMPARA EL TITULO',
 'SUPERFICIE EN m2',
 'FECHA DE REGISTRO',
 'AUTORIDAD QUE EMITE EL ACTO',
 'CLAVE DE REGIÓN HIDROLÓGICA',
 'NOMBRE DE REGIÓN HIDROLÓGICA',
 'ESTADO',
 'NOMBRE DE ESTADO',
 'CLAVE DE MUNICIPIO',
 'NOMBRE DE MUNICIPIO',
 'CLAVE DE CUENCA HIDROLÓGICA',
 'NOMBRE DE CUENCA HIDROLÓGICA',
 'VOLUMEN ANUAL EN m3',
 'GRADOS LATITUD',
 'MINUTOS LATITUD',
 'SEGUNDOS LATITUD',
 'GRADOS LONGITUD',
 'MINUTOS LONGITUD',
 'SEGUNDOS LONGITUD',
 'CLAVE DE ACUIFERO QUE MENCIONA EL TITULO',
 'ACUIFERO QUE MENCIONA EL TITULO',
 'NÚMERO DE ANEXO',
 'CLAVE DE ACUIFERO HOMOLOGADO',
 'NOMBRE DE ACUIFERO HOMOLOGADO',
 'Latitud',
 'Longitud',
 'PubPrivEjid',
 'ACUIFERO',
 'Recarga_total_media_anual',
 'Descarga_natural_media_anual',
 'Volumen_consesionado_de_aguas_subterraneas',
 'Volumen_de_extraccion_de_alumbramiento',
 'Volumen_de_extraccion_de_agua_pendiente_de_titulacion',
 'M_CVE_MUN',
 'M_NOM_MUN',
 'A_id_acuif',
 'A_nom_acuif',
 'Comp_Mun',
 'Comp_Acu',
 'Filtro']

In [42]:
df2 = df[df['Filtro'] == 'Coincide']

## Descripción Estadística

In [43]:
df_desc = df2.describe()
# Se muestra un preview de los datos
df_desc

,Column1,VOLUMEN DE EXTRACCIÓN ANUAL DE AGUAS NACIONALES QUE AMPARA EL TITULO EN m3,APROVECHAMIENTOS SUPERFICIALES QUE AMPARA EL TITULO,VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUPERFICIALES EN m3,APROVECHAMIENTOS SUBTERRÁNEOS QUE AMPARA EL TITULO,VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUBTERRÁNEOS EN m3,PUNTOS DE DESCARGA QUE AMPARA EL TITULO,VOLUMEN DE DESCARGA DIARIO EN m3,ZONAS FEDERALES QUE AMPARA EL TITULO,SUPERFICIE EN m2,...,Longitud,Recarga_total_media_anual,Descarga_natural_media_anual,Volumen_consesionado_de_aguas_subterraneas,Volumen_de_extraccion_de_alumbramiento,Volumen_de_extraccion_de_agua_pendiente_de_titulacion,M_CVE_MUN,A_id_acuif,Comp_Mun,Comp_Acu
count,10871.000000,1.087100e+04,10871.000000,1.087100e+04,10871.000000,1.087100e+04,10871.000000,10871.000000,10871.000000,10871.000000,...,10871.000000,1.086600e+04,1.086600e+04,1.086600e+04,1.086600e+04,1.086600e+04,10871.000000,10871.000000,10871.0,10871.0
mean,6373.780057,1.056661e+07,0.143133,7.268596e+06,8.029344,3.298012e+06,0.061264,14115.205593,0.061264,306.319566,...,-99.972525,1.819055e+08,1.660366e+07,1.401624e+08,7.731199e+07,7.502814e+06,25.704443,1912.305400,1.0,1.0
std,3661.616396,7.215650e+07,0.990167,5.034408e+07,41.508512,2.181434e+07,0.424329,97765.383972,0.424329,2121.644617,...,0.301095,1.334639e+08,1.739869e+07,9.244000e+07,6.359378e+07,7.332790e+07,14.150601,5.724205,0.0,0.0
min,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,-100.799000,2.500000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1901.000000,1.0,1.0
25%,3199.500000,1.500000e+03,0.000000,0.000000e+00,1.000000,1.500000e+03,0.000000,0.000000,0.000000,0.000000,...,-100.174722,5.390000e+07,6.200000e+06,5.676750e+07,8.825110e+06,0.000000e+00,9.000000,1912.000000,1.0,1.0
50%,6346.000000,2.774000e+04,0.000000,0.000000e+00,1.000000,2.774000e+04,0.000000,0.000000,0.000000,0.000000,...,-99.975278,1.437000e+08,7.900000e+06,1.020170e+08,5.124970e+07,7.718000e+03,26.000000,1912.000000,1.0,1.0
75%,9476.000000,1.560000e+05,0.000000,0.000000e+00,2.000000,1.560000e+05,0.000000,0.000000,0.000000,0.000000,...,-99.734722,3.367000e+08,1.800000e+07,2.435680e+08,1.506010e+08,2.160000e+04,38.000000,1914.000000,1.0,1.0
max,12816.000000,5.102885e+08,7.000000,3.559320e+08,295.000000,1.543565e+08,3.000000,691200.000000,3.000000,15000.000000,...,-99.166667,3.367000e+08,7.310000e+07,2.435680e+08,1.506010e+08,7.260000e+08,51.000000,1924.000000,1.0,1.0

In [44]:
# Se quita la columna de estado pues no tiene mucha relevancia ya que solo esta Nuevo León y demás columnas innecesrias
df_filt= df_desc.drop(labels = ['APROVECHAMIENTOS SUBTERRÁNEOS QUE AMPARA EL TITULO',
                                'APROVECHAMIENTOS SUPERFICIALES QUE AMPARA EL TITULO',
                                'PUNTOS DE DESCARGA QUE AMPARA EL TITULO',
                                'ZONAS FEDERALES QUE AMPARA EL TITULO',
                                'Longitud',
                                'M_CVE_MUN',
                                'A_id_acuif',
                                'Comp_Mun',
                                'Column1',
                                'Comp_Acu'], axis = 1)

In [45]:
df_filt2 = df_filt.groupby(by=['CLAVE DE MUNICIPIO']).sum()
# Se obtiene el análisis descriptivo para los atributos numéricos relevantes
df_filt2.describe()

,VOLUMEN DE EXTRACCIÓN ANUAL DE AGUAS NACIONALES QUE AMPARA EL TITULO EN m3,VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUPERFICIALES EN m3,VOLUMEN DE EXTRACCIÓN ANUAL DE APROVECHAMIENTOS SUBTERRÁNEOS EN m3,VOLUMEN DE DESCARGA DIARIO EN m3,SUPERFICIE EN m2,CLAVE DE REGIÓN HIDROLÓGICA,ESTADO,CLAVE DE CUENCA HIDROLÓGICA,VOLUMEN ANUAL EN m3,GRADOS LATITUD,...,SEGUNDOS LONGITUD,CLAVE DE ACUIFERO QUE MENCIONA EL TITULO,NÚMERO DE ANEXO,CLAVE DE ACUIFERO HOMOLOGADO,Latitud,Recarga_total_media_anual,Descarga_natural_media_anual,Volumen_consesionado_de_aguas_subterraneas,Volumen_de_extraccion_de_alumbramiento,Volumen_de_extraccion_de_agua_pendiente_de_titulacion
count,8.000000e+00,8.000000e+00,8.000000e+00,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000e+00,8.000000,...,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00
mean,7.415097e+07,5.169444e+07,2.245813e+07,101743.948696,3537.370523,1376.643725,1373.125000,1485.936327,2.816232e+06,1377.697693,...,1382.710862,2763.793385,1399.480694,2794.003701,1378.099421,1.486100e+08,1.740165e+07,1.098167e+08,6.277418e+07,1.008589e+08
std,1.779750e+08,1.241522e+08,5.382216e+07,240481.148416,5948.228149,3836.315443,3837.726799,3800.882573,7.782393e+06,3835.883030,...,3833.892824,3405.261560,3828.413281,3331.117215,3835.721191,1.333725e+08,2.367734e+07,9.561359e+07,6.160040e+07,2.538642e+08
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,3.174636,0.000000,0.000000,0.000000e+00,0.612545,...,0.000000,-1.000000,1.000000,5.724205,0.551454,1.086600e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.528250e+03,0.000000e+00,8.528250e+03,0.000000,0.000000,19.250000,19.000000,0.000000,8.399625e+03,24.476750,...,16.290306,1333.150402,1.000000,1909.250000,24.813917,4.105000e+07,4.652716e+06,4.257834e+07,6.621549e+06,5.788500e+03
50%,9.187000e+04,5.435500e+03,9.187000e+04,5435.500000,153.159783,24.000000,19.000000,38.286036,4.010400e+04,25.000000,...,28.511777,1907.000000,2.654310,1912.152700,25.470778,1.385819e+08,1.225183e+07,9.722850e+07,5.742174e+07,1.623300e+04
75%,2.596408e+07,1.803747e+07,7.927095e+06,35027.750188,4308.983463,27.981372,19.000000,326.438907,1.262691e+05,25.500000,...,47.985500,2234.250000,90.402699,1916.500000,26.233757,2.206041e+08,1.754902e+07,1.660138e+08,9.563424e+07,2.395908e+07
max,5.102885e+08,3.559320e+08,1.543565e+08,691200.000000,15000.000000,10871.000000,10871.000000,10871.000000,2.207520e+07,10871.000000,...,10871.000000,10871.000000,10871.000000,10871.000000,10871.000000,3.367000e+08,7.310000e+07,2.435680e+08,1.506010e+08,7.260000e+08

In [66]:
vol_an= df2['VOLUMEN ANUAL EN m3'].sum()
vol_an #Total de volumen de agua anual

774486721.7

# Datos Población obtenidos de la [secretaría de economía de Nuevo León](http://datos.nl.gob.mx/n-l-poblacion-total-y-por-municipio/)

In [47]:
df_pob = pd.read_excel('Downloads/Semana_i/Datos/1Población de NL INEGI.xlsx')
df_pob

      Municipio  Periodo  Población
0       Abasolo     1990       1373
1       Abasolo     1995       1945
2       Abasolo     2000       2514
3       Abasolo     2005       2746
4       Abasolo     2010       2791
..          ...      ...        ...
352  Villaldama     2000       4247
353  Villaldama     2005       4105
354  Villaldama     2010       4113
355  Villaldama     2015       4080
356  Villaldama     2020       3573

[357 rows x 3 columns]

In [59]:
# Filtramos los datos para el periodo de tiempo del 2020
df_20= df_pob[df_pob['Periodo'] == 2020]
df_20

                    Municipio  Periodo  Población
6                     Abasolo     2020       2974
13                 Agualeguas     2020       3382
20                    Allende     2020      35289
27                    Anáhuac     2020      18030
34                    Apodaca     2020     656464
41                  Aramberri     2020      14992
48                 Bustamante     2020       3661
55          Cadereyta Jiménez     2020     122337
62                     Carmen     2020     104478
69                   Cerralvo     2020       7340
76                      China     2020       9930
83          Ciénega de Flores     2020      68747
90              Doctor Arroyo     2020      36088
97                Doctor Coss     2020       1360
104           Doctor González     2020       3256
111                   Galeana     2020      40903
118                    García     2020     397205
125             General Bravo     2020       5506
132          General Escobedo     2020     481213
139             General Terán     2020      14109
146           General Treviño     2020       1808
153          General Zaragoza     2020       6282
160            General Zuazua     2020     102149
167                 Guadalupe     2020     643143
174                   Hidalgo     2020      16086
181                  Higueras     2020       1386
188               Hualahuises     2020       7026
195                  Iturbide     2020       3298
202                    Juárez     2020     471523
209       Lampazos de Naranjo     2020       5351
216                   Linares     2020      84666
223               Los Aldamas     2020       1407
230              Los Herreras     2020       1959
237               Los Ramones     2020       5389
244                     Marín     2020       5119
251            Melchor Ocampo     2020       1483
258            Mier y Noriega     2020       7652
265                      Mina     2020       6048
272              Montemorelos     2020      67428
279                 Monterrey     2020    1142994
286                     Parás     2020        906
293                 Pesquería     2020     147624
300                   Rayones     2020       2377
307           Sabinas Hidalgo     2020      34709
314          Salinas Victoria     2020      86766
321  San Nicolás de los Garza     2020     412199
328    San Pedro Garza García     2020     132169
335            Santa Catarina     2020     306322
342                  Santiago     2020      46784
349                Vallecillo     2020       1552
356                Villaldama     2020       3573

## Descripción estadística

In [49]:
df_20.describe()

       Periodo     Población
count     51.0  5.100000e+01
mean    2020.0  1.134204e+05
std        0.0  2.226685e+05
min     2020.0  9.060000e+02
25%     2020.0  3.477500e+03
50%     2020.0  1.410900e+04
75%     2020.0  9.445750e+04
max     2020.0  1.142994e+06

In [50]:
Nom, Periodo, Pobnl = df_20.sum()
Pobnl #Población de Nuevo León

5784442

In [57]:
df_DOMES = df2[df2['USO QUE AMPARA EL TITULO'] == 'DOMÉSTICO']['VOLUMEN ANUAL EN m3'].sum()
df_Pub = df2[df2['USO QUE AMPARA EL TITULO'] == 'PÚBLICO URBANO']['VOLUMEN ANUAL EN m3'].sum()
df_tot = df_Pub + df_DOMES

In [65]:
# Cantidad de agua per capita en Nuevo León en el 2020
agua_per_capita= df_tot/Pobnl
agua_per_capita

19.341080000456397